name: Publish Honkit Docs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Generate SUMMARY.md
        run: |
          echo "# Summary" > SUMMARY.md
          echo "" >> SUMMARY.md
          echo "* [Introduction](README.md)" >> SUMMARY.md
          for file in docs/*.md; do
            if [ -f "$file" ]; then
              title=$(basename "$file" .md | tr '_' ' ' | sed 's/\b\w/\u&/g')
              echo "* [$title]($file)" >> SUMMARY.md
            fi
          done

      - name: Build Honkit Site
        run: |
          npx honkit build
          echo "Build completed. Checking for Mermaid diagrams..."
          find _book -name "*.html" -exec grep -l "mermaid" {} \;

      - name: Add .nojekyll
        run: touch _book/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
