name: Simple Reviewdog Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test-reviewdog:
    name: Test Reviewdog Basic Functionality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Test reviewdog with simple output
        run: |
          echo "src/common/SBOMSigner.cpp:102:10: warning: test message from reviewdog" | \
          reviewdog -efm="%f:%l:%c: %tarning: %m" -name="test" -reporter=github-pr-review -fail-on-error=false
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}