name: Unified Reviewdog Format Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  unified-format-check:
    name: Unified Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y clang-format
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run unified clang-format check
        run: |
          # Get all changed C++ files
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} | grep -E '\.(c|cpp|h|hpp)$' || true)
          echo "Checking files: $FILES"
          
          if [ -n "$FILES" ]; then
            # Process all files together in one diff
            TEMP_DIFF=$(mktemp)
            FOUND_ISSUES=false
            
            for file in $FILES; do
              if [ -f "$file" ]; then
                echo "Processing: $file"
                if ! clang-format "$file" | diff -u "$file" - >> "$TEMP_DIFF"; then
                  FOUND_ISSUES=true
                fi
              fi
            done
            
            if [ "$FOUND_ISSUES" = true ]; then
              echo "Found formatting issues, sending unified diff:"
              cat "$TEMP_DIFF"
              echo ""
              echo "--- Sending to reviewdog ---"
              cat "$TEMP_DIFF" | reviewdog -f=diff -name="clang-format-unified" -reporter=github-pr-review -fail-on-error=false
            else
              echo "No formatting issues found"
            fi
            
            rm -f "$TEMP_DIFF"
          else
            echo "No C++ files changed"
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}